[package]
name = "vtx-security-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
serde_json = "1.0"
vtx-security = { path = "../vtx-security" }

[[bin]]
name = "vtx-security"
path = "src/main.rs"
